import { IEntitySchemaConfig, EPropertyTypes } from '../../types';

const Booking: IEntitySchemaConfig = {
  entity: 'booking',
  schema_version: 'v4',
  properties: [
    {
      id: 'category',
      name: 'category',
      type: EPropertyTypes.STRING,
      nullable: false,
    },
    {
      id: 'category_strings',
      name: 'category_strings',
      type: EPropertyTypes.ARRAY,
      data_type: EPropertyTypes.STRING,
      nullable: false,
    },
    {
      id: 'categories',
      name: 'categories',
      type: EPropertyTypes.COLLECTION,
      additional_properties: [
        {
          id: 'id',
          name: 'id',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'name',
          name: 'name',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'category_type',
          name: 'category_type',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
      ],
      nullable: false,
    },
    {
      id: 'addon_charge',
      name: 'addon_charge',
      type: EPropertyTypes.DICTIONARY,
      nullable: false,
      additional_properties: [
        {
          id: 'id',
          name: 'id',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'name',
          name: 'name',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'suggested_price_start',
          name: 'suggested_price_start',
          type: EPropertyTypes.NUMBER,
          nullable: false,
        },
        {
          id: 'suggested_price_end',
          name: 'suggested_price_end',
          type: EPropertyTypes.NUMBER,
          nullable: false,
        },
        {
          id: 'rate',
          name: 'rate',
          type: EPropertyTypes.NUMBER,
          nullable: false,
        },
        {
          id: 'quantity',
          name: 'quantity',
          type: EPropertyTypes.NUMBER,
          nullable: false,
        },
      ],
    },
    {
      id: 'booking_type',
      name: 'booking_type',
      nullable: false,
      type: EPropertyTypes.OBJECT,
      additional_properties: [
        {
          id: 'id',
          name: 'id',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'name',
          name: 'name',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'duration_type',
          name: 'duration_type',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
      ],
    },
    {
      id: 'guest_name',
      name: 'guest_name',
      nullable: false,
      type: EPropertyTypes.STRING,
    },
    {
      id: 'guest_tiers',
      name: 'guest_tiers',
      nullable: false,
      type: EPropertyTypes.ARRAY,
      data_type: EPropertyTypes.STRING,
    },
    {
      id: 'tail_number',
      name: 'tail_number',
      nullable: false,
      type: EPropertyTypes.STRING,
    },
    {
      id: 'pickup_time',
      name: 'pickup_time',
      nullable: false,
      type: EPropertyTypes.NUMBER,
    },
    {
      id: 'dropoff_time',
      name: 'dropoff_time',
      nullable: false,
      type: EPropertyTypes.NUMBER,
    },
    {
      id: 'pickup_date',
      name: 'pickup_date',
      nullable: false,
      type: EPropertyTypes.NUMBER,
    },
    {
      id: 'dropoff_date',
      name: 'dropoff_date',
      nullable: false,
      type: EPropertyTypes.NUMBER,
    },
    {
      id: 'pickup_address',
      name: 'pickup_address',
      nullable: false,
      type: EPropertyTypes.OBJECT,
      additional_properties: [
        {
          id: 'id',
          name: 'id',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'provider',
          name: 'provider',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'name',
          name: 'name',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'lat',
          name: 'lat',
          nullable: false,
          type: EPropertyTypes.NUMBER,
        },
        {
          id: 'lng',
          name: 'lng',
          nullable: false,
          type: EPropertyTypes.NUMBER,
        },
      ],
    },
    {
      id: 'dropoff_address',
      name: 'dropoff_address',
      nullable: false,
      type: EPropertyTypes.OBJECT,
      link: 'pickup_address',
    },
    {
      id: 'pickup_counter',
      name: 'pickup_counter',
      nullable: false,
      type: EPropertyTypes.OBJECT,
      additional_properties: [
        {
          id: 'id',
          name: 'id',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'provider',
          name: 'provider',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'name',
          name: 'name',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'location_code',
          name: 'location_code',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'type',
          name: 'type',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'status',
          name: 'status',
          nullable: false,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'lat',
          name: 'lat',
          nullable: false,
          type: EPropertyTypes.NUMBER,
        },
        {
          id: 'lng',
          name: 'lng',
          nullable: false,
          type: EPropertyTypes.NUMBER,
        },
      ],
    },
    {
      id: 'dropoff_counter',
      name: 'dropoff_counter',
      nullable: false,
      type: EPropertyTypes.OBJECT,
      link: 'pickup_counter',
    },
    {
      id: 'ra_number',
      name: 'ra_number',
      nullable: false,
      type: EPropertyTypes.STRING,
    },
    {
      id: 'vehicle_search_filter',
      name: 'vehicle_search_filter',
      nullable: true,
      type: EPropertyTypes.OBJECT,
      additional_properties: [
        {
          id: 'search_text',
          name: 'search_text',
          nullable: true,
          type: EPropertyTypes.STRING,
        },
        {
          id: 'search_pills',
          name: 'search_pills',
          nullable: true,
          type: EPropertyTypes.ARRAY,
          data_type: EPropertyTypes.STRING,
        },
        {
          id: 'filter_options',
          name: 'filter_options',
          nullable: true,
          type: EPropertyTypes.ARRAY,
          data_type: EPropertyTypes.STRING,
        },
        {
          id: 'filter_pill',
          name: 'filter_pill',
          nullable: true,
          type: EPropertyTypes.DICTIONARY,
          additional_properties: []
        },
      ],
    },
    {
      id: 'vehicle_search_selected_counter_id',
      name: 'vehicle_search_selected_counter_id',
      nullable: false,
      type: EPropertyTypes.STRING,
    },
    {
      id: 'vehicle_search_selected_counter_name',
      name: 'vehicle_search_selected_counter_name',
      nullable: false,
      type: EPropertyTypes.STRING,
    },
    {
      id: 'vehicle_search_advanced_option_filter',
      name: 'vehicle_search_advanced_option_filter',
      nullable: true,
      type: EPropertyTypes.DICTIONARY,
      additional_properties: []
    },
    {
      id: 'payment',
      name: 'payment',
      nullable: true,
      type: EPropertyTypes.OBJECT,
      additional_properties: [
        {
          id: 'total_charge',
          name: 'total_charge',
          nullable: true,
          type: EPropertyTypes.NUMBER,
        },
        {
          id: 'total_auth',
          name: 'total_auth',
          nullable: true,
          type: EPropertyTypes.NUMBER,
        },
        {
          id: 'total_paid',
          name: 'total_paid',
          nullable: true,
          type: EPropertyTypes.NUMBER,
        },
        {
          id: 'remaining_balance',
          name: 'remaining_balance',
          nullable: true,
          type: EPropertyTypes.NUMBER,
        },
        {
          id: 'direct_bills',
          name: 'direct_bills',
          nullable: true,
          type: EPropertyTypes.ARRAY,
          data_type: EPropertyTypes.STRING,
        },
        {
          id: 'credit_cards',
          name: 'credit_cards',
          nullable: true,
          type: EPropertyTypes.ARRAY,
          data_type: EPropertyTypes.STRING,
        },
      ],
    },
    {
      id: 'guest_instruction',
      name: 'guest_instruction',
      nullable: true,
      type: EPropertyTypes.STRING,
    },
  ],
};

export default Booking;
