import { IEntitySchemaConfig, EPropertyTypes } from '../../types';

const Movement: IEntitySchemaConfig = {
  entity: 'movement',
  schema_version: 'v4',
  properties: [
    {
      id: 'status',
      name: 'status',
      type: EPropertyTypes.STRING,
      nullable: false,
    },
    {
      id: 'category',
      name: 'category',
      type: EPropertyTypes.STRING,
      nullable: false,
    },
    {
      id: 'category_strings',
      name: 'category_strings',
      type: EPropertyTypes.ARRAY,
      data_type: EPropertyTypes.STRING,
      nullable: false,
    },
    {
      id: 'categories',
      name: 'categories',
      type: EPropertyTypes.COLLECTION,
      nullable: false,
      additional_properties: [
        {
          id: 'id',
          name: 'id',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'name',
          name: 'name',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'category_type',
          name: 'category_type',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
      ],
    },
    {
      id: 'driver',
      name: 'driver',
      type: EPropertyTypes.OBJECT,
      nullable: true,
      additional_properties: [
        {
          id: 'label',
          name: 'label',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'value',
          name: 'value',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'data',
          name: 'data',
          type: EPropertyTypes.ANY,
          nullable: false,
        },
        {
          id: 'isNew',
          name: 'isNew',
          type: EPropertyTypes.BOOLEAN,
          nullable: false,
        },
      ],
    },
    {
      id: 'vendor',
      name: 'vendor',
      type: EPropertyTypes.OBJECT,
      nullable: true,
      link: 'driver',
    },
    {
      id: 'estimated_cost',
      name: 'estimated_cost',
      type: EPropertyTypes.STRING,
      nullable: true,
    },
    {
      id: 'vehicles_and_destinations',
      name: 'vehicles_and_destinations',
      type: EPropertyTypes.COLLECTION,
      nullable: false,
      additional_properties: [
        {
          id: 'movement_purpose',
          name: 'movement_purpose',
          type: EPropertyTypes.STRING,
          nullable: false,
        },
        {
          id: 'booking',
          name: 'booking',
          type: EPropertyTypes.OBJECT,
          nullable: false,
          link: 'driver',
        },
        {
          id: 'other_purpose',
          name: 'other_purpose',
          type: EPropertyTypes.STRING,
          nullable: true,
        },
        {
          id: 'maintenance',
          name: 'maintenance',
          type: EPropertyTypes.OBJECT,
          nullable: true,
          link: 'driver',
        },
        {
          id: 'destination_type',
          name: 'destination_type',
          type: EPropertyTypes.STRING,
          nullable: true,
        },
        {
          id: 'counter',
          name: 'counter',
          type: EPropertyTypes.OBJECT,
          nullable: true,
          link: 'driver',
        },
        {
          id: 'partner',
          name: 'partner',
          type: EPropertyTypes.OBJECT,
          nullable: true,
          link: 'driver',
        },
        {
          id: 'vendor',
          name: 'vendor',
          type: EPropertyTypes.OBJECT,
          nullable: true,
          link: 'driver',
        },
        {
          id: 'specific_address',
          name: 'specific_address',
          type: EPropertyTypes.OBJECT,
          nullable: true,
          additional_properties: [
            {
              id: 'country',
              name: 'country',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'address',
              name: 'address',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'city',
              name: 'city',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'street',
              name: 'street',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'latitude',
              name: 'latitude',
              type: EPropertyTypes.NUMBER,
              nullable: false,
            },
            {
              id: 'longitude',
              name: 'longitude',
              type: EPropertyTypes.NUMBER,
              nullable: false,
            },
            {
              id: 'state',
              name: 'state',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'zip_code',
              name: 'zip_code',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
          ],
        },
        {
          id: 'selected_vehicles',
          name: 'selected_vehicles',
          type: EPropertyTypes.OBJECT,
          nullable: false,
          additional_properties: [
            {
              id: 'id',
              name: 'id',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'code',
              name: 'code',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'vin',
              name: 'vin',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'year',
              name: 'year',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'exterior_color',
              name: 'exterior_color',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'make_name',
              name: 'make_name',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'model_name',
              name: 'model_name',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'status',
              name: 'status',
              type: EPropertyTypes.STRING,
              nullable: false,
            },
            {
              id: 'vehicle_class',
              name: 'vehicle_class',
              type: EPropertyTypes.ANY,
              nullable: false,
            },
          ],
        },
      ],
    },
  ],
};

export default Movement;
